display_errors=On
display_startup_errors=On
error_reporting=E_ALL
log_errors=On
expose_php=Off
session.use_strict_mode=1
session.cookie_httponly=1
session.cookie_samesite=Lax
memory_limit=256M
upload_max_filesize=16M
post_max_size=16M
date.timezone=Europe/Bucharest
